# Generated by Django 5.1.3 on 2024-11-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0002_remove_user_user'),
        ('uauth', '0003_update_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uauth.User'),
        ),
    ]
