# Generated by Django 5.1.3 on 2024-11-26 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0004_merge_0002_remove_user_user_0003_update_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluators', to=settings.AUTH_USER_MODEL),
        ),
    ]
