# Generated by Django 5.1.3 on 2024-11-21 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('Sklypas', 'Sklypas'), ('Butas', 'Butas'), ('Namas', 'Namas'), ('Sodas', 'Sodas'), ('Kotedžas', 'Kotedžas'), ('Kita', 'Kita')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=255)),
                ('meta_value', models.CharField(max_length=255)),
                ('ev_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.object')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.object')),
            ],
        ),
    ]
