# Generated by Django 5.1.3 on 2024-11-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('evaluate_order', 'Can evaluate order'), ('view_evaluator_orders', 'Can view evaluator orders')]},
        ),
    ]
