# Generated by Django 5.1.3 on 2024-11-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_agency_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
    ]
