# Generated by Django 5.1.3 on 2024-12-02 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluator_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Naujas', 'Naujas'), ('Patvirtintas', 'Patvirtintas'), ('Vykdomas', 'Vykdomas'), ('Įvykdytas', 'Įvykdytas'), ('Nepateiktas', 'Nepateiktas')], max_length=45),
        ),
    ]
