# Generated by Django 5.1.3 on 2024-12-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_evaluator_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='object_images/')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('Lokacija', 'Lokacija'), ('Priedas', 'Priedas'), ('Planas', 'Planas'), ('Kita', 'Kita')], max_length=45)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.object')),
            ],
        ),
    ]
