# Generated by Django 5.1.3 on 2025-01-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='file_path',
            field=models.FileField(default='', upload_to='uploaded_documents/'),
            preserve_default=False,
        ),
    ]
