# Generated by Django 5.1.3 on 2025-01-15 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_uploadeddocument_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='NearbyOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_organizations', to='orders.object')),
            ],
        ),
    ]
