# Generated by Django 5.1.3 on 2025-01-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_object_latitude_object_longitude_nearbyorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyorganization',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
