# Generated by Django 5.1.3 on 2025-01-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_nearbyorganization_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyorganization',
            name='distance',
            field=models.DecimalField(max_digits=8),
        ),
    ]
