# Generated by Django 5.1.3 on 2025-01-22 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_nearbyorganization_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyorganization',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, blank=True, null=True)),
                ('customer_surname', models.CharField(max_length=255, blank=True, null=True)),
                ('customer_phone', models.CharField(max_length=20, blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('engineering', models.TextField(blank=True, null=True)),
                ('addictions', models.TextField(blank=True, null=True)),
                ('floor_plan', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('valuation_methodology', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]