# Generated by Django 5.1.3 on 2025-02-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_nearbyorganization_distance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('žemas', 'žemas'), ('vidutinis', 'vidutinis'), ('aukštas', 'aukštas')], default=0, max_length=45),
            preserve_default=False,
        ),
    ]
