# Generated by Django 5.1.3 on 2025-03-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('Žemas', 'Žemas'), ('Vidutinis', 'Vidutinis'), ('Aukštas', 'Aukštas')], max_length=45),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Nebaigtas', 'Nebaigtas'), ('Naujas', 'Naujas'), ('Patvirtintas', 'Patvirtintas'), ('Vykdomas', 'Vykdomas'), ('Įvykdytas', 'Įvykdytas'), ('Nepateiktas', 'Nepateiktas')], max_length=45),
        ),
    ]
