# Generated by Django 5.1.3 on 2025-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_submission', 'Ataskaitos Pateikimas'), ('report_approval', 'Ataskaitos Patvirtinimas'), ('report_rejection', 'Ataskaitos Atmetimas'), ('order_assignment', 'Užsakymo pavedimas'), ('event', 'Kalendoriaus pranešimas'), ('system', 'Sistemos pranešimas')], max_length=20),
        ),
    ]
