# Generated by Django 5.1.3 on 2025-04-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_submission', 'Ataskaitos Pateikimas'), ('report_approval', 'Ataskaitos Patvirtinimas'), ('report_rejection', 'Ataskaitos Atmetimas'), ('order_assignment', 'Užsakymo pavedimas'), ('event', 'Kalendoriaus pranešimas'), ('system', 'Sistemos pranešimas'), ('event_transfer', 'Calendar Event Transfer')], max_length=20),
        ),
    ]
